### PR TITLE
BUG: with multipage and with AJAX navigation

### PR DESCRIPTION
**Pull request by linuxonrails**
When you click in slidemenu button the page is changed to the first page (old) saved in HTML.

Test-case: index.html multipage.

When you click in 'Go to the page "two"'
   And you click in Slidermenu button
Then You should be in page two

  but you are in page one (?!)

### CODE REVIEW

**Comment by tegansnyder** [comment]
@linuxonrails I see what you are seeing... taking a look now. BTW thanks for pointing out these issues that's what makes github shine :)

**Comment by tegansnyder** [comment]
@linuxonrails try this code:
https://github.com/tegansnyder/JQuery-Mobile-Slide-Menu/tree/multi-page-support

Note I had to disable page transitions to get the flicker to stop.

UPDATE: I just tried this from my iPhone and it doesn't work... it seems to work in chrome... must be some timing issue.

**Comment by alexhung-mccann** [comment]
Any update on this issue? I'm having same problem and after modifying the js to work with my pages, I'm still getting the page being changed back to the first page.

**Comment by tegansnyder** [comment]
@alexhung-mccann I haven't had time to really sit down and tackle this issue. Have you tried using the separate branch. https://github.com/tegansnyder/JQuery-Mobile-Slide-Menu/tree/multi-page-support

For kicks download it in it's entirety and try running it.

**Comment by joanscript** [comment]
I added a preventDefault event and it solved this problem:

```
    $(document).on("swipeleft",":jqmData(role='page')", function(event) {
            slidemenu(sm);
            event.stopImmediatePropagation();
            event.preventDefault();
    });
    $(document).on("swiperight",":jqmData(role='page')", function(event){
            slidemenu(sm);
            event.stopImmediatePropagation();
            event.preventDefault();
    });
    $(document).on("click", ":jqmData(slidemenu)", function(event) {
            slidemenu(sm);
            event.stopImmediatePropagation();
            event.preventDefault();
    });
```

**Comment by linuxonrails** [comment]
Thankx joanscript

**Comment by tegansnyder** [comment]
Please try the latest code. I updated it to include support for multiple pages, ajax, and multiple slide menus.

**Pull request closed without merging**
